# MkDocs configuration
# Used as base - look for .yml files with INHERIT
site_name: Blylei 的博客
site_url: "https://blog.blylei.tech"
use_directory_urls: false
docs_dir: docs/
# repo_name: blylei/blylei.github.io
# repo_url: https://github.com/blylei/blylei.github.io

theme:
    name: material
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
      - navigation.top
    locale: zh_CN
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

nav:
  - 关于我: about.md
  - MySQL相关:
      - 基础篇: mysql/basic/index.md
      - 高性能篇: mysql/hp/index.md
      - 高可用篇: mysql/ha/index.md
  - Redis相关:
      - 基础: redis/basic/index.md
      - 哨兵-Sentinel: redis/sentinel/index.md
      - 集群-Cluster: redis/cluster/index.md
  - MongoDB相关:
      - 基础: mongodb/basic/index.md
      - 复制集: mongodb/rs/index.md
      - 分片集群: mongodb/sc/index.md
  - 已归档: archiver/index.md
