# MkDocs configuration
# Used as base - look for .yml files with INHERIT
site_name: Blylei 的博客
site_url: "https://blog.blylei.tech"
use_directory_urls: false
docs_dir: docs/
# repo_name: blylei/blylei.github.io
# repo_url: https://github.com/blylei/blylei.github.io

theme:
    name: mkdocs
    locale: zh_CN
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s


nav:
  - 关于我: about.md
  - MySQL相关:
      - 基础:
          - basic/index.md
          - basic/server/network.md
          - basic/server/docker.md
          - basic/server/virtual-appliance.md
          - basic/server/aws.md
          - basic/server/easy-install.md
          - basic/server/dbaas.md

      - 高性能:
          - hp/client/index.md
          - hp/client/mysql.md
          - hp/client/mongodb.md
          - hp/client/postgresql.md
          - hp/client/proxysql.md
          - hp/client/aws.md
      - 高可用:
          - ha/client/azure.md
          - ha/client/google.md
          - ha/client/linux.md
          - ha/client/external.md
          - ha/client/haproxy.md
          - ha/client/remote.md
  - Redis相关:
      - using/index.md
      - using/interface.md
      - using/alerting.md
      - using/backup.md
      - using/query-analytics.md
      - using/dbaas.md
      - using/security-threat-tool.md
  - MongoDB相关:
      - how-to/index.md
      - how-to/configure.md
      - how-to/upgrade.md
      - how-to/secure.md
      - how-to/optimize.md
      - how-to/annotate.md
      - how-to/render-dashboard-images.md
      - how-to/extend-metrics.md
      - how-to/troubleshoot.md
  - 归档: archiver/index.md
