# MkDocs configuration
# Used as base - look for .yml files with INHERIT
site_name: Blylei 的博客
site_url: "https://blog.blylei.tech"
use_directory_urls: false
docs_dir: docs/
# repo_name: blylei/blylei.github.io
# repo_url: https://github.com/blylei/blylei.github.io

theme:
    name: mkdocs
    locale: zh_CN
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s


nav:
  - 关于我: about.md
  - MySQL相关:
      - 基础篇: mysql/basic/index.md
      - 高性能篇: mysql/hp/index.md
      - 高可用篇: mysql/ha/index.md
  - Redis相关:
      - 基础:
          - basic/index.md
          - basic/server/network.md
          - basic/server/docker.md
          - basic/server/virtual-appliance.md
          - basic/server/aws.md
          - basic/server/easy-install.md
          - basic/server/dbaas.md

      - 哨兵-Sentinel:
          - hp/client/index.md
          - hp/client/mysql.md
          - hp/client/mongodb.md
          - hp/client/postgresql.md
          - hp/client/proxysql.md
          - hp/client/aws.md
      - 集群-Cluster:
          - ha/client/azure.md
          - ha/client/google.md
          - ha/client/linux.md
          - ha/client/external.md
          - ha/client/haproxy.md
          - ha/client/remote.md
  - MongoDB相关:
      - 基础:
          - basic/index.md
          - basic/server/network.md
          - basic/server/docker.md
          - basic/server/virtual-appliance.md
          - basic/server/aws.md
          - basic/server/easy-install.md
          - basic/server/dbaas.md

      - 复制集:
          - hp/client/index.md
          - hp/client/mysql.md
          - hp/client/mongodb.md
          - hp/client/postgresql.md
          - hp/client/proxysql.md
          - hp/client/aws.md
      - 分片集群:
          - ha/client/azure.md
          - ha/client/google.md
          - ha/client/linux.md
          - ha/client/external.md
          - ha/client/haproxy.md
          - ha/client/remote.md
  - 已归档: archiver/index.md
